### ISSUE TITLE
Unable to build and run the project

### ISSUE THREAD

**Issue by thaindq** [udacity/Sunshine-Version-2#117]
I tried to build and run the app and got this error. Cannot find symbol variable a829e78b3d3559e6bc1eafde8e8419f5

When I double click on it, it points to this line in SunshineSyncAdapter.java file:
import android.content.SyncRequest;

I have no idea how to fix it.

**Comment by thaindq** [comment]
Nevermind. The issue has been resolved.

**Comment by adienthu** [comment]
Hi @d3ver0x I'm facing the same issue. How did you resolve this ?

**Comment by falvarez** [comment]
Check this link:

http://stackoverflow.com/questions/33226978/could-not-find-property-xxxx-on-com-android-build-gradle-appextension-decorate

In my case, api key quotes were mispelled in gradle.properties file
