### ISSUE TITLE
Gradle build error with OPEN_WEATHER_MAP_API_KEY

### ISSUE THREAD

**Issue by khat33b** [udacity/Sunshine-Version-2#166]
I am getting error in `BuildConfig.java` when I add this code

```
buildTypes.each {
            it.buildConfigField 'String', 'OPEN_WEATHER_MAP_API_KEY', '239d9c7bc3c3c59947d0ce1a566c3d9a'
        }
```

In `BuildConfig.java`, the line is being generated as `public static final String OPEN_WEATHER_MAP_API_KEY = 239d9c7bc3c3c59947d0ce1a566c3d9a;`
This is without the quotes. on the key.

**Comment by ghost** [comment]
Try this , it should work. 

buildTypes.each {
        it.buildConfigField 'String', 'OPEN_WEATHER_MAP_API_KEY',    "\"239d9c7bc3c3c59947d0ce1a566c3d9a \""
    }

Also,I am getting this error when i run -
EGL_emulation: eglSurfaceAttrib not implemented

**Comment by ghost** [comment]
weather data is not being dislpayed on the emulator,, could you tell me where to put the URL for this openweatherAPI ?

**Comment by khat33b** [comment]
That worked. Thanks! The URL is put in the `doInBackground` method in the `FetchWeatherTask` inner class in the `ForecastFragment` file. See lesson 2 for more details.

**Comment by Kenny31** [comment]
I've tried the same thing but still getting an error.
```Error:(21, 0) Cannot invoke method c6df6708fbb6b300f0a08ee3c8b08e9d() on null object```
Please help.
here's the screenshot of the screen.
![error3](https://user-images.githubusercontent.com/25009367/32456687-7628c00c-c34c-11e7-8f50-f38bb7db1dab.jpg)
