### ISSUE TITLE
Refresh Button didn't showed up after updating code.

### ISSUE THREAD

**Issue by lauriewu1** [udacity/Sunshine-Version-2#210]
after updating the forcastFragment.java file, string.xml, main.xml, forecastfragment.xml. I still don't see refresh button show up on the menu bar. The menu bar does show up but only have setting button. I've tried to compare my code with codes presented in lesson "Quiz: refresh button behavior " few times now and can not see if I'm missing any code.

**Comment by ghost** [comment]
what api are you using on genimotion ?

2016-04-26 18:54 GMT-03:00 lauriewu1 notifications@github.com:
