### ISSUE TITLE
when i open it

### ISSUE THREAD

**Issue by YxmCute** [udacity/Sunshine-Version-2#305]
Error:Could not find property 'MyOpenWeatherMapApiKey' on com.android.build.gradle.AppExtension_Decorated@181e15ee.

**Comment by pharrellyhy** [comment]
This is used by OpenWeatherMap API when you fetching the weather information from the website. So you need to generate your own API key on their website https://openweathermap.org/appid#get. Then, change 'MyOpenWeatherMapApiKey' to "\"your_key_here\"".

**Comment by brndmg** [comment]
Follow the instructions here:
https://github.com/udacity/Sunshine-Version-2/#open-weather-map-api-key-is-required

**Comment by Kenny31** [comment]
Facing the same problem. I have generated my API and I am still getting error. 
![error1](https://user-images.githubusercontent.com/25009367/32456420-88728ba4-c34b-11e7-9723-aed591c235db.jpg)
![error2](https://user-images.githubusercontent.com/25009367/32456421-88e41b66-c34b-11e7-9f1a-eeb94f773d46.jpg)
