### ISSUE TITLE
Cursor populated with phantom-like data

### ISSUE THREAD

**Issue by ersin-ertan** [udacity/Sunshine-Version-2#33]
In branch [4.06_test_weather_table](https://github.com/udacity/Sunshine-Version-2/tree/4.06_test_weather_table) with the file:
[app/src/androidTest/java/com/example/android/sunshine/app/data/TestDb.java](https://github.com/udacity/Sunshine-Version-2/blob/4.06_test_weather_table/app/src/androidTest/java/com/example/android/sunshine/app/data/TestDb.java)
Where are these android_metadata,  and the sqlite_sequence entries coming from in the Cursor? Additional entries/deletions are needed to get the HashSet to empty and resolve the test.  

```
final HashSet<String> tableNameHashSet = new HashSet<String>();
        tableNameHashSet.add("android_metadata");
        tableNameHashSet.add(WeatherContract.LocationEntry.TABLE_NAME);
        tableNameHashSet.add("sqlite_sequence");
        tableNameHashSet.add(WeatherContract.WeatherEntry.TABLE_NAME);
```

**Comment by marcochin** [comment]
hey, those are just the default tables that get created with every sqlite db. Try to replace the select statement on line 65 with this:
"SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' AND name NOT LIKE 'android_metadata' ". Your solution should works too.

**Comment by TysonMatlhoma** [comment]
thanks, i'm still trying to setup my sqlite database

Regards,
Amos
